name: wisp_ai
description: "WispAI – The Future of Effortless Conversations 💬✨"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  logger: ^2.5.0
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.17
  cloud_firestore: ^5.6.4
  firebase_ui_auth: ^1.16.1
  url_launcher: ^6.3.1
  flutter_tts: ^4.2.2
  flutter_markdown: ^0.7.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-LightItalic.ttf
          style: italic
