// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7krB_HFmAuhbJdG4xoomda9HVGREuKSg',
    appId: '1:854188567459:web:0b0f0c5d7b461b858c4816',
    messagingSenderId: '854188567459',
    projectId: 'flutterlenz',
    authDomain: 'flutterlenz.firebaseapp.com',
    storageBucket: 'flutterlenz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcGIWS1lE16dQHCRGqc36RkgweltgmeOE',
    appId: '1:854188567459:android:73b77973293939838c4816',
    messagingSenderId: '854188567459',
    projectId: 'flutterlenz',
    storageBucket: 'flutterlenz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnsqq4-D6ZBZV6vo7Ww9V9C21QltU4oTw',
    appId: '1:854188567459:ios:337e879548af71ee8c4816',
    messagingSenderId: '854188567459',
    projectId: 'flutterlenz',
    storageBucket: 'flutterlenz.firebasestorage.app',
    androidClientId: '854188567459-h7tvcoebpivc2mqhfba665e2v74ba6gp.apps.googleusercontent.com',
    iosClientId: '854188567459-enarni5eap27nvjic6vdfto91ldnhsr1.apps.googleusercontent.com',
    iosBundleId: 'com.technolenz.wispai',
  );
}
